In [1]:
import networkx as nx
import numpy as np

# paper's algorithm

In [2]:
A =np.array([[0,1,1,1],
             [1,0,1,0],
             [1,1,0,0],
             [1,0,0,0]])

D =np.array([[3,0,0,0],
             [0,2,0,0],
             [0,0,2,0],
             [0,0,0,1]])

D_inv = np.linalg.inv(D)
W = np.matmul(A,D_inv)

In [3]:
W

array([[0.        , 0.5       , 0.5       , 1.        ],
       [0.33333333, 0.        , 0.5       , 0.        ],
       [0.33333333, 0.5       , 0.        , 0.        ],
       [0.33333333, 0.        , 0.        , 0.        ]])

In [4]:
alpha = 0.2

In [6]:
p0 = np.array([0.25,0.25,0.25,0.25])[:,np.newaxis]

In [10]:
P=p0

In [36]:
P=alpha* p0 + (1-alpha)*np.matmul(W,P)
P

array([[0.36340195],
       [0.24484539],
       [0.24484539],
       [0.14690727]])

In [9]:
alpha*np.matmul(  np.linalg.inv(np.eye(4) - (1-alpha)*W), p0)

array([[0.36340206],
       [0.24484536],
       [0.24484536],
       [0.14690722]])

# networkx

In [3]:
G = nx.Graph([('A',"B"),('A','C'),('A','D'),('C','B'),])
#G.add_nodes_from('ABCD')

In [66]:
A = nx.convert_matrix.to_numpy_matrix(G)
A

matrix([[0., 1., 1., 1.],
        [1., 0., 1., 0.],
        [1., 1., 0., 0.],
        [1., 0., 0., 0.]])

In [67]:
nx.pagerank(G,alpha=0.8)

{'A': 0.363402632640262,
 'B': 0.2448452059786188,
 'C': 0.2448452059786188,
 'D': 0.14690695540250032}